# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('qa', '0003_add_mark_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answervotes',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='answervotes',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answervotes',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='questionvotes',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='questionvotes',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
        migrations.DeleteModel(
            name='AnswerVotes',
        ),
        migrations.DeleteModel(
            name='QuestionVotes',
        ),
    ]
